spring:
  # 数据库连接地址
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/epidemic_management?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      initial-size: 5 # 初始连接数
      max-active: 20 # 最大连接池
      max-wait: 6000 # 最大等待时长，毫秒
      min-idle: 1 # 最小连接池
      test-while-idle: true # 连接时检测
      test-on-borrow: false # 申请连接时执行检测
      test-on-return: false # 规划连接时执行检测
      validation-query: SELECT 1 FROM DUAL # 连接检测
      time-between-eviction-runs-millis: 60000 # 检测间隔时间，毫秒
      min-evictable-idle-time-millis: 300000 # 连接池最小生存时间，毫秒
      max-evictable-idle-time-millis: 900000 # 连接池最大生存时间，毫秒

    # 配置监控统计拦截的filters，stat:监控统计；log4j：日志记录；wall：防御sql注入
    filters: stat, wall, log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  redis:
    database: 0
    host: 192.168.10.100
    port: 6379
    timeout: 2000 # 连接超时时间
    lettuce:
      pool:
        max-active: -1 # 最大连接数
        max-idle: 8 # 最大空闲连接数
        min-idle: 2 # 最小空闲连接数
        max-wait: -1ms # 最大阻塞等待时间

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  # 使用MySQL数据库
  helper-dialect: mysql
  # 开启合理化，避免查询不存在的页码
  reasonable: true
server:
  port: 8080
